# Generated by Django 2.0.6 on 2018-06-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.SmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('cpf_cnpj', models.IntegerField(db_column='CPF_CNPJ', unique=True)),
                ('razao', models.CharField(blank=True, db_column='RAZAO', max_length=100, null=True)),
                ('endereco', models.CharField(db_column='ENDERECO', max_length=80)),
                ('cep', models.CharField(db_column='CEP', max_length=20)),
                ('email', models.CharField(db_column='EMAIL', max_length=200)),
                ('telefone', models.CharField(db_column='TELEFONE', max_length=11)),
                ('celular', models.CharField(blank=True, db_column='CELULAR', max_length=11, null=True)),
            ],
            options={
                'db_table': 'Cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.SmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('cpf_cnpj', models.IntegerField(db_column='CPF_CNPJ', unique=True)),
                ('razao', models.CharField(blank=True, db_column='RAZAO', max_length=100, null=True)),
                ('endereco', models.CharField(db_column='ENDERECO', max_length=80)),
                ('cep', models.CharField(db_column='CEP', max_length=20)),
                ('email', models.CharField(db_column='EMAIL', max_length=200)),
                ('telefone', models.CharField(db_column='TELEFONE', max_length=11)),
                ('celular', models.CharField(blank=True, db_column='CELULAR', max_length=11, null=True)),
                ('pessoa_contato', models.CharField(blank=True, db_column='PESSOA_CONTATO', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Fornecedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.SmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='NOME', max_length=100)),
                ('cpf', models.IntegerField(db_column='CPF')),
                ('cargo', models.SmallIntegerField(db_column='CARGO')),
                ('login', models.CharField(db_column='LOGIN', max_length=100)),
                ('senha', models.CharField(db_column='SENHA', max_length=50)),
            ],
            options={
                'db_table': 'Funcionario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Materiaprima',
            fields=[
                ('id', models.SmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='NOME', max_length=60)),
                ('forma_emb', models.CharField(db_column='FORMA_EMB', max_length=60)),
                ('peso', models.CharField(db_column='PESO', max_length=20)),
                ('unid_medida', models.CharField(db_column='UNID_MEDIDA', max_length=50)),
                ('quantidade', models.IntegerField(db_column='QUANTIDADE')),
                ('quantidade_min', models.IntegerField(db_column='QUANTIDADE_MIN')),
                ('descricao', models.CharField(db_column='DESCRICAO', max_length=500)),
                ('data_recebimento', models.DateField(db_column='DATA_RECEBIMENTO')),
            ],
            options={
                'db_table': 'MateriaPrima',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ordemdeproducao',
            fields=[
                ('id', models.SmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_column='Descricao', max_length=500)),
            ],
            options={
                'db_table': 'OrdemDeProducao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.SmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('data_pedido', models.DateField(db_column='DATA_PEDIDO')),
                ('valor', models.CharField(blank=True, db_column='VALOR', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedidomp',
            fields=[
                ('id', models.SmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('data_pedido', models.DateField(db_column='DATA_PEDIDO')),
                ('data_prevista', models.DateField(db_column='DATA_PREVISTA')),
                ('descricao', models.CharField(blank=True, db_column='DESCRICAO', max_length=500, null=True)),
                ('valor', models.CharField(blank=True, db_column='VALOR', max_length=20, null=True)),
            ],
            options={
                'db_table': 'PedidoMP',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='NOME', max_length=60)),
                ('forma_emb', models.CharField(db_column='FORMA_EMB', max_length=60)),
                ('peso', models.CharField(db_column='PESO', max_length=20)),
                ('unid_medida', models.CharField(db_column='UNID_MEDIDA', max_length=50)),
                ('preco', models.CharField(blank=True, db_column='PRECO', max_length=10, null=True)),
                ('quantidade', models.IntegerField(blank=True, db_column='QUANTIDADE', null=True)),
                ('desc_produto', models.CharField(db_column='DESC_PRODUTO', max_length=500)),
            ],
            options={
                'db_table': 'Produto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.SmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='NOME', max_length=100)),
            ],
            options={
                'db_table': 'Setor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Statusordemproducao',
            fields=[
                ('id', models.SmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('status_nome', models.CharField(db_column='STATUS_NOME', max_length=30)),
            ],
            options={
                'db_table': 'StatusOrdemProducao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoproduto',
            fields=[
                ('id', models.SmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='NOME', max_length=100)),
            ],
            options={
                'db_table': 'TipoProduto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tiposeguimento',
            fields=[
                ('id', models.SmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='NOME', max_length=100)),
            ],
            options={
                'db_table': 'TipoSeguimento',
                'managed': False,
            },
        ),
    ]
